name: gh-set-secret

on:
  workflow_dispatch:
  
env:
  secret_name: HELLO_WORLD
  secret_body: "Hello World!"

jobs:
  gh-set-secret:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2.4.0
      - name: gh auth login
        shell: bash
        run: gh auth login --with-token <<< "${{ secrets.GITHUB_TOKEN }}"
      - name: gh secret set
        shell: bash
        run: gh secret set "${{ env.secret_name }}" --env=sandbox --body="${{ env.secret_body }}"
  gh-test-secret:
    needs: [gh-set-secret]
    runs-on: ubuntu-latest
    env:
      secret: ${{ secrets.HELLO_WORLD }}
    steps:
      - name: echo secret
        shell: bash
        run: echo "$HELLO_WORLD"
