# Prerequisites:
# - Create a secret with your PAT token. Permissions needed: repo (all) and read:org
# - Create the HELLO_WORLD secret in your environment with some dummy initial value
#
# Notes:
# - You can tell that it works because it masks the secret_body in the echo secret step after it creates the secret 😄
# - If you don't want to have to pass --repo to gh secret set, then put the actions/checkout@v2 step before the gh secret set step

name: gh-set-secret

on:
  workflow_dispatch:

env:
  pat_token: ${{ secrets.PAT_TOKEN }} # Permissions: repo (all) and read:org
  repo_secret_name: repo_secret
  actions_secret_name: actions_secret
  codespaces_secret_name: codespaces_secret
  dependabot_secret_name: dependabot_secret
  org_secret_name: org_secret
  user_secret_name: user_secret
  deploymentEnvironment_secret_name: deploymentEnvironment_secret
  secret_body: "Hello World!"
  deployment_environment: sandbox

jobs:
  gh-set-secrets:
    runs-on: ubuntu-latest
    steps:
      # Upgrade gh cli to use the --app parameter (added in version 2.6.0 (2022-03-15))
      - name: Upgrade gh cli to latest stable
        shell: bash
        run: |
          gh --version
          brew update || true
          brew doctor || true
          brew install gh
          gh --version
      - name: gh auth login
        shell: bash
        run: gh auth login --with-token <<< $pat_token
      - name: gh secret set
        shell: bash
        run: |
          repository='${{ github.repository }}'
          org='${{ github.repository_owner }}'

          # Permissions: repo (all) and read:org
          echo "Setting repository secret (default app: actions)..."
          gh secret set "$repo_secret_name" --repo $repository \
            --body "$secret_body$repo_secret_name" || true
          echo "Done."

          # Permissions: repo (all) and read:org
          echo "Setting repository actions secret..."
          gh secret set "$actions_secret_name" --repo $repository \
            --body "$secret_body$actions_secret_name" \
            --app actions || true
          echo "Done."

          # Permissions: repo (all) and read:org
          echo "Setting repository dependabot secret..."
          gh secret set "$dependabot_secret_name" --repo $repository \
            --body "$secret_body$dependabot_secret_name" \
            --app dependabot || true
          echo "Done."

          # Permissions: repo (all) and read:org
          echo "Setting deployment environment secret..."
          gh secret set "$deploymentEnvironment_secret_name" --repo $repository \
            --env "$deployment_environment" \
            --body "$secret_body$deploymentEnvironment_secret_name" || true
          echo "Done."

          # Permissions: repo (all), write:org, admin:public_key
          echo "Setting organization secret..."
          gh secret set "$org_secret_name" --org $org \
            --body "$secret_body$org_secret_name" || true
          echo "Done."

          # Permissions: repo (all), read:org, codespace:secrets
          echo "Setting user secret..."
          gh secret set "$user_secret_name" --user \
            --body "$secret_body$user_secret_name" || true
          echo "Done."

          # Permissions: repo (all), read:org, codespace:secrets
          echo "Setting user codespaces secret..."
          gh secret set "$codespaces_secret_name" --user  \
            --body "$secret_body$codespaces_secret_name" \
            --app codespaces || true
          echo "Done."

          # This is not supported in version 2.6.0
          # echo "Setting organization codespaces secret..."
          # gh secret set "$codespaces_secret_name" --org $org  \
          #   --body "$secret_body$codespaces_secret_name" \
          #   --app codespaces || true
          # echo "Done."

          # This is not supported in version 2.6.0
          # echo "Setting repository codespaces secret..."
          # gh secret set "$codespaces_secret_name" --repo $repository  \
          #   --body "$secret_body$codespaces_secret_name" \
          #   --app codespaces || true
          # echo "Done."

          echo "Sleeping 5s to wait for secrets propagate..."
          sleep 5s
          echo "Done."

  gh-test-secrets:
    needs: [gh-set-secrets]
    runs-on: ubuntu-latest
    if: always()
    environment:
      name: sandbox
    env:
      repo_secret: ${{ secrets.repo_secret }}
      actions_secret: ${{ secrets.actions_secret }}
      codespaces_secret: ${{ secrets.codespaces_secret }}
      org_secret: ${{ secrets.org_secret }}
      user_secret: ${{ secrets.user_secret }}
      deploymentEnvironment_secret: ${{ secrets.deploymentEnvironment_secret }}
    steps:
      - name: echo secrets
        shell: bash
        run: |
          echo "Repository secret: $repo_secret"
          echo "Repository actions secret: $actions_secret"
          echo "Repository dependabot secret: Cannot be viewed from Actions"
          echo "Deployment Environment secret: $deploymentEnvironment_secret"
          echo "Organization secret: $org_secret"
          echo "User secret: $user_secret"
          echo "Organization codespaces secret: $codespaces_secret"
