# Prerequisites:
# - Create a secret with your PAT token. Permissions needed: repo (all), admin:org, admin:public_key, codespace:secrets
#
# Notes:
# - If you don't want to have to pass --repo to gh secret set, then put the actions/checkout@v2 step before the gh secret set step

name: gh secret set examples

on:
  workflow_dispatch:

env:
  pat_token: ${{ secrets.PAT_TOKEN }}
  repo_secret_name: repo_secret
  actions_secret_name: actions_secret
  codespaces_secret_name: codespaces_secret
  dependabot_secret_name: dependabot_secret
  org_secret_name: org_secret
  user_secret_name: user_secret
  deploymentEnvironment_secret_name: deploymentEnvironment_secret
  secret_body: "Hello World!"
  deployment_environment: sandbox

jobs:
  gh-set-secrets:
    runs-on: ubuntu-latest
    steps:
      # Upgrade gh cli to use the --app parameter (added in version 2.6.0 (2022-03-15))
      - name: Upgrade gh cli to the latest version
        uses: philip-gai/upgrade-gh-cli@v1
      - name: gh secret set
        shell: bash
        run: |
          echo "Running gh auth login"
          gh auth login --with-token <<< $pat_token

          repository='${{ github.repository }}'
          org='elastico-group'

          # Permissions: repo (all) and read:org
          echo "Setting repository actions secret..."
          gh secret set "$repo_secret_name" --repo $repository \
            --body "$secret_body$repo_secret_name"
          echo "Done."

          # Permissions: repo (all) and read:org
          echo "Setting repository actions secret another way..."
          gh secret set "$actions_secret_name" --repo $repository \
            --body "$secret_body$actions_secret_name" \
            --app actions
          echo "Done."

          # Permissions: repo (all) and read:org
          echo "Setting deployment environment secret..."
          gh secret set "$deploymentEnvironment_secret_name" --repo $repository \
            --env "$deployment_environment" \
            --body "$secret_body$deploymentEnvironment_secret_name"
          echo "Done."

          # Permissions: repo (all) and read:org
          echo "Setting repository dependabot secret..."
          gh secret set "$dependabot_secret_name" --repo $repository \
            --body "$secret_body$dependabot_secret_name" \
            --app dependabot
          echo "Done."

          # Permissions: repo (all), read:org, codespace:secrets
          echo "Setting user codespaces secret..."
          gh secret set "$user_secret_name" --user \
            --body "$secret_body$user_secret_name"
          echo "Done."

          # Permissions: repo (all), read:org, codespace:secrets
          echo "Setting user codespaces secret another way..."
          gh secret set "$codespaces_secret_name" --user  \
            --body "$secret_body$codespaces_secret_name" \
            --app codespaces
          echo "Done."

          # Permissions: repo (all), admin:org, admin:public_key
          echo "Setting organization actions secret (only works in org repos, not user repos)..."
          gh secret set "$org_secret_name" --org $org \
            --body "$secret_body$org_secret_name"
          echo "Done."

          echo "Setting organization actions secret another way..."
          gh secret set "$org_secret_name" --org $org \
            --body "$secret_body$org_secret_name" \
            --app actions
          echo "Done."

          echo "Setting organization dependabot secret..."
          gh secret set "$codespaces_secret_name" --org $org  \
            --body "$secret_body$codespaces_secret_name" \
            --app dependabot
          echo "Done."

          # This is not supported in version 2.6.0
          gh secret set "$codespaces_secret_name" --org $org  \
            --body "$secret_body$codespaces_secret_name" \
            --app codespaces || true

          # This is not supported in version 2.6.0
          gh secret set "$codespaces_secret_name" --repo $repository  \
            --body "$secret_body$codespaces_secret_name" \
            --app codespaces || true
