name: gh-set-secret

on:
  workflow_dispatch:
  
env:
  secret_name: HELLO_WORLD
  secret_body: "Hello World!"

jobs:
  gh-set-secret:
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.PAT_TOKEN }}
    steps:
      - name: gh secret set env
        shell: bash
        run: gh secret set "${{ env.secret_name }}" --env "sandbox" --body "${{ env.secret_body }}" --repo "philip-gai/philip-gai"
  gh-test-secret:
    needs: [gh-set-secret]
    runs-on: ubuntu-latest
    env:
      secret: ${{ secrets.HELLO_WORLD }}
    steps:
      - name: echo secret
        shell: bash
        run: echo "$HELLO_WORLD"
