name: Rerun workflow

on:
  workflow_dispatch:
    inputs:
      runId:
        required: true
        type: string

env:
  runId: ${{ github.event.inputs.runId }}

jobs:
  retry_workflow_job:
    name: Rerun ${{ github.event.inputs.runId }}
    runs-on: ubuntu-latest
    steps:
      # Upgrade gh cli so we can use the job parameter
      - name: Upgrade gh cli to latest stable
        shell: pwsh
        run: |
          gh --version
          brew update
          brew doctor
          brew install gh
          gh --version
      - name: "Rerun ${{ github.event.inputs.runId }}"
        shell: pwsh
        env:
          # GITHUB_TOKEN with actions: write will NOT work
          # PAT Token must have workflow scope
          GH_CLI_TOKEN: ${{ secrets.PAT_TOKEN }}
        run: |
          echo "Running gh auth login..."
          $env:GH_CLI_TOKEN | gh auth login --with-token
          if(!$?) { exit 1 }

          echo "Retrying run..."
          echo "gh run rerun $env:runId --failed --repo $env:GITHUB_REPOSITORY"
          gh run rerun $env:runId --failed --repo $env:GITHUB_REPOSITORY
          if(!$?) { exit 1 }
