name: Rerun failed workflow test

on:
  workflow_dispatch:
    inputs:
      maxAttempts:
        required: true
        type: number
        default: 3

jobs:
  attempt_job:
    name: "Attempt ${{ github.run_attempt }} of ${{ github.event.inputs.maxAttempts }}"
    runs-on: ubuntu-latest
    steps:
      - name: Run script attempt 
        id: run_script
        shell: pwsh
        run: |
          $attempt = [int]$env:GITHUB_RUN_ATTEMPT
          $maxAttempts = [int]$env:maxAttempts
          $nextAttempt = $attempt + 1
          echo "::set-output name=nextAttempt::$nextAttempt"

          if($attempt -eq $maxAttempts) {
            Write-Host "Succeeded on attempt $attempt"
          } else {
            Write-Error "Failed on attempt $attempt"
            exit 1
          }

  rerun_workflow_job:
    name: Rerun ${{ github.run_id }}
    runs-on: ubuntu-latest
    needs: attempt_job
    if: failure() && ( needs.attempt_job.outputs.nextAttempt <= github.event.inputs.maxAttempts )
    env:
      attempt: ${{ needs.attempt_job.outputs.nextAttempt }}
    steps:
      - name: "Trigger Rerun ${{ needs.attempt_job.outputs.nextAttempt }} of ${{ github.event.inputs.maxAttempts }}"
        shell: pwsh
        env:
          # GITHUB_TOKEN with actions: write will NOT work
          # PAT Token must have workflow scope
          GH_CLI_TOKEN: ${{ secrets.PAT_TOKEN }}
        run: |
          echo "Logging in workflow..."
          $env:GH_CLI_TOKEN | gh auth login --with-token
          if($?) { exit 1 }

          echo "Triggering rerun attempt $nextAttempt"
          echo "gh workflow run rerun-workflow.yml --raw-field runId=$env:GITHUB_RUN_ID --raw-field jobName=attempt_job --repo $GITHUB_REPOSITORY"
          gh workflow run rerun-workflow.yml --raw-field runId=$env:GITHUB_RUN_ID --raw-field jobName=attempt_job --repo $GITHUB_REPOSITORY
          if($?) { exit 1 }
