name: Rerun workflow

on:
  workflow_dispatch:
    inputs:
      attempt:
        required: true
        type: number
        default: 1
      maxAttempts:
        required: true
        type: number
        default: 3

env:
  attempt: ${{ github.event.inputs.attempt }}
  maxAttempts: ${{ github.event.inputs.maxAttempts }}

jobs:
  attempt_job:
    name: "Attempt ${{ github.event.inputs.attempt }} of ${{ github.event.inputs.maxAttempts }}"
    runs-on: ubuntu-latest
    outputs:
      nextAttempt: ${{ steps.run_script.outputs.nextAttempt }}
    steps:
      - name: Run script
        id: run_script
        shell: pwsh
        run: |
          $attempt = [int]$env:attempt
          $maxAttempts = [int]$env:maxAttempts
          $nextAttempt = $attempt + 1
          echo "::set-output name=nextAttempt::$nextAttempt"

          if($attempt -eq $maxAttempts) {
            Write-Host "Succeeded on attempt $attempt"
          } else {
            Write-Error "Failed on attempt $attempt"
            exit 1
          }

  retry_workflow_job:
    name: Retry Job
    runs-on: ubuntu-latest
    needs: attempt_job
    if: failure() && ( needs.attempt_job.outputs.nextAttempt <= github.event.inputs.maxAttempts )
    env:
      attempt: ${{ needs.attempt_job.outputs.nextAttempt }}
    steps:
      - name: "Trigger Attempt ${{ needs.attempt_job.outputs.nextAttempt }} of ${{ github.event.inputs.maxAttempts }}"
        shell: bash
        env:
          # GITHUB_TOKEN with actions: write will NOT work
          # PAT Token must have workflow scope
          GH_CLI_TOKEN: ${{ secrets.PAT_TOKEN }}
        run: |
          echo "Retrying workflow..."
          gh auth login --with-token <<< $GH_CLI_TOKEN
          echo "Triggering attempt $attempt"
          echo "gh run rerun $GITHUB_RUN_ID --repo $GITHUB_REPOSITORY"
          gh run rerun $GITHUB_RUN_ID --repo $GITHUB_REPOSITORY
