name: Retryable workflow

on:
  workflow_call:
    inputs:
      attempt:
        required: true
        type: number
      maxAttempts:
        required: true
        type: number
        default: 5
  workflow_dispatch:
    inputs:
      attempt:
        required: true
        type: number
        default: 0
      maxAttempts:
        required: true
        type: number
        default: 5

env:
  attempt: ${{ inputs.attempt }}
  maxAttempts: ${{ inputs.maxAttempts }}

jobs:
  attempt_job:
    name: Attempt Job
    runs-on: ubuntu-latest
    outputs:
      nextAttempt: ${{ steps.run_script.outputs.nextAttempt }}
    steps:
      - name: Run script
        id: run_script
        shell: pwsh
        run: |
          $nextAttempt = $attempt + 1
          echo "::set-output name=nextAttempt::$nextAttempt"
          if($attempt -eq $maxAttempts - 1) {
            Write-Host "Succeeded on attempt $attempt"
          } else {
            Write-Error "Failed on attempt $attempt"
            exit 1
          }

  retry_workflow_job:
    name: Retry Job
    runs-on: ubuntu-latest
    needs: attempt_job
    if: failure() && (${{ needs.attempt_job.outputs.nextAttempt }} < ${{ env.maxAttempts }})
    env:
      attempt: ${{ needs.attempt_job.outputs.nextAttempt }}
    steps:
      - name: Retry
        shell: bash
        run: |
          echo "Retrying workflow..."
          echo "Triggering attempt $attempt"
          gh workflow run retry-workflow.yml \
            -f attempt=$attempt \
            -f maxAttempts=$maxAttempts \
            --ref $GITHUB_REF \
            --repo $GITHUB_REPOSITORY
          exit 1
