name: Retryable workflow

on:
  workflow_call:
    inputs:
      attempt:
        required: true
        type: number
      maxAttempts:
        required: true
        type: number
        default: 5
  workflow_dispatch:
    inputs:
      attempt:
        required: true
        type: number
        default: 1
      maxAttempts:
        required: true
        type: number
        default: 5

env:
  attempt: ${{ github.event.inputs.attempt }}
  maxAttempts: ${{ github.event.inputs.maxAttempts }}

permissions:
  actions: write

jobs:
  attempt_job:
    name: 'Attempt ${{ github.event.inputs.attempt }} of ${{ github.event.inputs.maxAttempts }}'
    runs-on: ubuntu-latest
    outputs:
      nextAttempt: ${{ steps.run_script.outputs.nextAttempt }}
    steps:
      - name: Run script
        id: run_script
        shell: pwsh
        run: |
          $attempt = [int]$env:attempt
          $maxAttempts = [int]$env:maxAttempts
          $nextAttempt = $attempt + 1
          echo "::set-output name=nextAttempt::$nextAttempt"

          if($attempt -eq $maxAttempts - 1) {
            Write-Host "Succeeded on attempt $attempt"
          } else {
            Write-Error "Failed on attempt $attempt"
            exit 1
          }

  retry_workflow_job:
    name: Retry Job
    runs-on: ubuntu-latest
    needs: attempt_job
    if: failure() && ( needs.attempt_job.outputs.nextAttempt <= github.event.inputs.maxAttempts )
    env:
      attempt: ${{ needs.attempt_job.outputs.nextAttempt }}
    steps:
      - name: Upgrade gh cli
        shell: pwsh
        run: |
          gh --version
          brew install gh
          gh --version
      - name: 'Trigger Attempt ${{ needs.attempt_job.outputs.nextAttempt }} of ${{ github.event.inputs.maxAttempts }}'
        shell: pwsh
        env:
          GH_CLI_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh --version
          $attempt = [int]$env:attempt
          $maxAttempts = [int]$env:maxAttempts

          echo "Retrying workflow..."
          $env:GH_CLI_TOKEN | gh auth login --with-token

          echo "Triggering attempt $attempt"
          echo "Executing...
            gh workflow run retry-workflow.yml
              --raw-field attempt=$attempt
              --raw-field maxAttempts=$maxAttempts
              --ref $env:GITHUB_REF
              --repo $env:GITHUB_REPOSITORY
          "
          gh workflow run retry-workflow.yml `
            --raw-field attempt=$attempt `
            --raw-field maxAttempts=$maxAttempts `
            --ref $env:GITHUB_REF `
            --repo $env:GITHUB_REPOSITORY
          exit 1
