name: Example Workflow with Retries

on:
  workflow_call:
    inputs:
      attempt:
        required: true
        type: number
  workflow_dispatch:

env:
  maxAttempts: 5

jobs:
  attempt_job:
    name: Attempt Job
    runs-on: ubuntu-latest
    outputs:
      nextAttempt: ${{ steps.run_script.outputs.nextAttempt }}
    steps:
      - name: Run script
        id: run_script
        shell: pwsh
        run: |
          $attempt = "${{ inputs.attempt }}" ? [int]"${{ inputs.attempt }}" : 0
          $nextAttempt = $attempt + 1
          echo "::set-output name=nextAttempt::$nextAttempt"
          $maxAttempts = ${{ env.maxAttempts }}
          if($attempt -eq $maxAttempts -1) {
            Write-Host "Succeeded on attempt $attempt"
          } else {
            Write-Error "Failed on attempt $attempt"
            exit 1
          }

  retry_workflow_job:
    name: Retry Job
    runs-on: ubuntu-latest
    needs: attempt_job
    if: failure() && "${{ needs.attempt_job.outputs.nextAttempt }}" != "${{ env.maxAttempts }}"
    uses: ./.github/workflows/retry-workflow.yml
    with:
      attempt: ${{ needs.attempt_job.outputs.nextAttempt }}
