name: reusable-workflow

on:
  workflow_call:
    inputs:
      version:
        required: false
        type: string
  workflow_dispatch:

jobs:
  reusable_workflow_job:
    runs-on: ubuntu-latest
    steps:
      - name: echo version input
        shell: pwsh
        run: |
          $version = "${{ inputs.version }}"
          $message = If($version) { $version } Else { "Nothing" }
          Write-Host $message
