# Sends a reminder to assignees of all open issues in a repo using pwsh
# Uses the built-in GITHUB_TOKEN: https://docs.github.com/en/actions/security-guides/automatic-token-authentication

name: Send Reminders

on:
  schedule:
    - cron: "0 10 * * 1" # At 10:00 AM on Mondays
  workflow_dispatch: {}

jobs:
  send_reminders:
    name: Send Reminders
    runs-on: ubuntu-latest
    permissions:
      issues: write
    steps:
      - name: Run Send Reminders Script
        shell: pwsh
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          $repository = "${{ github.repository }}"

          Write-Host "Logging in..."
          $token | gh auth login --with-token

          Write-Host "Getting issues..."
          $issues = $(gh issue list -R $repository --state open --json "number,assignees" -L 500) | ConvertFrom-Json
          Write-Host "Found $($issues.Count) issues"

          Write-Host "Filtering out issues that are not assigned..."
          $issues = $issues | Where-Object {$_.Assignees -ne $null -and $_.Assignees.Count -gt 0}
          Write-Host "Found $($issues.Count) issues with assignees"

          foreach ($issue in $issues) {
            $assignee = $issue.Assignees[0].Login
            $reminderMessage = "
          @$assignee This is your friendly (automated) reminder!
          "

            Write-Host "Sending reminder to $assignee..."
            gh issue comment $issue.number `
              --body $reminderMessage `
              -R $repository

            if (!$?) {
              Write-Warning "Failed to send reminder to $assignee"
              continue
            }
          }

          Write-Host "Done"
