name: Shared composite action example

on:
  workflow_dispatch:

jobs:
  use-shared-composite-action:
    name: Use shared composite action example
    runs-on: ubuntu-latest
    steps:
      - name: Checkout composite actions repository
        uses: actions/checkout@v2
        with:
          repository: philip-gai/composite-actions
          path: composite-actions
      - name: Upgrade gh cli
        uses: ./composite-actions/.github/workflows/composite/upgrade-gh-cli
