name: Shared composite action example

on:
  workflow_dispatch:

jobs:
  use-shared-composite-action:
    name: Use shared composite action example
    runs-on: ubuntu-latest
    steps:
      - name: Upgrade gh cli to the latest version
        uses: philip-gai/upgrade-gh-cli@v1
