name: Update Homebrew on GitHub Actions Runner

on:
  workflow_dispatch:

jobs:
  update-homebrew:
    runs-on: ubuntu-latest
    steps:
      # Update homebrew to get the latest version of packages
      - name: Update homebrew
        shell: bash
        run: |
          brew --version
          brew update || true
          brew doctor || true
          brew --version
      - name: Install gh cli latest
        shell: bash
        run: |
          gh --version
          sudo apt update
          sudo apt install gh
          gh --version
