name: Update Homebrew Example

on:
  workflow_dispatch:

jobs:
  update-homebrew:
    runs-on: ubuntu-latest
    steps:
      # Update homebrew to get the latest version of packages
      - name: Update homebrew
        shell: bash
        run: |
          brew --version
          brew update || true
          brew doctor || true
          brew --version
