name: Update Homebrew on GitHub Actions Runner

on:
  workflow_dispatch:

jobs:
  update-homebrew:
    runs-on: ubuntu-latest
    steps:
      # Update homebrew to get the latest version of the gh cli
      - name: Update homebrew
        shell: bash
        run: |
          brew --version
          brew update || true
          brew doctor || true
          brew --version
      - name: Uninstall pre-installed gh cli
        shell: bash
        run: sudo apt remove gh works
      - name: Install gh cli latest
        shell: bash
        run: |
          brew install gh
          gh --version
