name: Upgrade APT Package Example

on:
  workflow_dispatch:

jobs:
  update-apt-packages:
    runs-on: ubuntu-latest
    steps:
      - name: Update Advanced Package Tool (APT)
        shell: bash
        run: sudo apt update
      - name: List upgradable packages
        shell: bash
        run: apt list --upgradable
      - name: Upgrade gh cli
        shell: bash
        run: |
          which gh
          gh --version
          # https://github.com/cli/cli/blob/trunk/docs/install_linux.md#debian-ubuntu-linux-raspberry-pi-os-apt 
          curl -fsSL https://cli.github.com/packages/githubcli-archive-keyring.gpg | sudo dd of=/usr/share/keyrings/githubcli-archive-keyring.gpg
          echo "deb [arch=$(dpkg --print-architecture) signed-by=/usr/share/keyrings/githubcli-archive-keyring.gpg] https://cli.github.com/packages stable main" | sudo tee /etc/apt/sources.list.d/github-cli.list > /dev/null
          sudo apt update
          sudo apt install gh
          gh --version
