name: Upgrade APT Package Example

on:
  workflow_dispatch:

jobs:
  update-apt-packages:
    runs-on: ubuntu-20.04
    steps:
      - name: Download latest gh cli package
        shell: bash
        run: |
          # https://github.com/cli/cli/blob/trunk/docs/install_linux.md#debian-ubuntu-linux-raspberry-pi-os-apt 
          curl -fsSL https://cli.github.com/packages/githubcli-archive-keyring.gpg | sudo dd of=/usr/share/keyrings/githubcli-archive-keyring.gpg
          echo "deb [arch=$(dpkg --print-architecture) signed-by=/usr/share/keyrings/githubcli-archive-keyring.gpg] https://cli.github.com/packages stable main" | sudo tee /etc/apt/sources.list.d/github-cli.list > /dev/null
      - name: Update Advanced Package Tool (APT)
        shell: bash
        run: sudo apt update
      - name: List upgradable packages
        shell: bash
        run: apt list --upgradable
      - name: Upgrade gh cli
        shell: bash
        run: |
          oldVersion=$(gh --version | grep "gh version")
          echo $oldVersion
          sudo apt install gh
          newVersion=$(gh --version | grep "gh version")
          echo $newVersion

          # Fails if the newVersion == oldVersion
          echo $newVersion | grep -v -q "$oldVersion"
